### ISSUE TITLE
Could not be constructed plugin error

### ISSUE THREAD

**Issue by Mohammed8339** [jaimeadf/BetterDiscordPlugins#197]
whenever I launch BD, I receive this error: 

SecretRingTone: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:308498)
    at Object.loadAddon (<anonymous>:4:270474)
    at Object.loadAddon (<anonymous>:4:307610)
    at FSWatcher.<anonymous> (<anonymous>:4:268333)

and now the secret ringtone won't start up, I've tried the common methods like reinstalling, restarting, retrying.
would be nice if you could fix this problem, if it's not a plugin problem, it would be nice if you could tell me what the problem is, thanks!

**Comment by EpicRG** [comment]
I had the same problem, but i fixed it by opening the raw file on the github repo and pasted the code into the .js file
