### ISSUE TITLE
GuildProfile Crashes discord

### ISSUE THREAD

**Issue by Serega007RU** [jaimeadf/BetterDiscordPlugins#204]
When I start the discord, I get an error in the console:
![image](https://user-images.githubusercontent.com/64780091/141015412-01677ec2-71d3-4b98-a93c-531ee0691e5d.png)

When trying to open the Guild profile, the discord crashes:
![image](https://user-images.githubusercontent.com/64780091/141014024-ac274b3a-83a9-4ff2-9476-5c4fc76dffab.png)
![image](https://user-images.githubusercontent.com/64780091/141015472-63234632-71b3-47fc-87e1-b859da96399e.png)

Full console log:
[discord.com-1636496856678.log](https://github.com/jaimeadf/BetterDiscordPlugins/files/7508358/discord.com-1636496856678.log)

Some technical information:
Discord: Stable 103981 (3436885)
BetterDiscord 1.2.4
Windows 10 64-Bit
GuildProfile v1.3.0

**Comment by jaimeadf** [comment]
It's working fine in the same discord version for me.

**Comment by Serega007RU** [comment]
How do I upgrade to the latest version? On https://github.com/jaimeadf/BetterDiscordPlugins/tree/release/src/GuildProfile I have version 1.3.0 downloaded, despite the fact that version 1.4.3 is signed on the download button

**Comment by jaimeadf** [comment]
That button is quite misleading. It is only a link to BetterDiscord's website, and the staff hasn't updated the version there.

To download the newest version open the [raw file](https://raw.githubusercontent.com/jaimeadf/BetterDiscordPlugins/release/dist/GuildProfile/GuildProfile.plugin.js) and click save as.

**Comment by Serega007RU** [comment]
Updated to 1.4.3, discord still crashes
![image](https://user-images.githubusercontent.com/64780091/141031103-54acb182-debd-462e-93b8-bd70aa135fc5.png)
![image](https://user-images.githubusercontent.com/64780091/141031210-f074dd15-461b-478c-b9ef-733612c31ddf.png)

**Comment by jaimeadf** [comment]
It is working fine for me.

**Comment by Serega007RU** [comment]
I do not know what else the problem may be, I have rechecked several times, the plugin has been updated to 1.4.3 for sure

**Comment by Serega007RU** [comment]
It turns out that it was necessary to update the ZeresPluginLibrary plugin, the problem is solved.
