### ISSUE TITLE
GuildProfile - Broken Since big discord update (Stable 110451 (c233a73))

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [jaimeadf/BetterDiscordPlugins#233]
Hi Since the big discord update GuildProfile Is missing from the context menu on discord.
![Screen Shot 2022-01-15 at 11 25 17 am](https://user-images.githubusercontent.com/2242880/149601149-1eef4b53-1c5f-4de7-9807-71a1c981abda.jpg)

![Screen Shot 2022-01-15 at 11 26 37 am](https://user-images.githubusercontent.com/2242880/149601152-6897c05a-a3ad-477b-b508-5371da8a1f5e.jpg)

I assume this is because BD is having issues with the "Guild Component"?
Also, they said each developer will have to update & fix their plugins after this mess.
![Screen Shot 2022-01-15 at 11 28 03 am](https://user-images.githubusercontent.com/2242880/149601202-8ba92625-0bf9-47f9-b683-6c819f408168.jpg)

**Comment by admiralaspergerss** [comment]
vouch

**Comment by Yilmaz4** [comment]
I don't have the Profile option either on right click menu, furthermore, "Server Profile" option when I click on the server name doesn't work. Discord literally f up BetterDiscord and its plugins.

**Comment by FlashlightET** [comment]
same

**Comment by jaimeadf** [comment]
I have pushed the fix.

**Comment by admiralaspergerss** [comment]
Thanks for the update
