### ISSUE TITLE
GuildProfile not working

### ISSUE THREAD

**Issue by x3221** [jaimeadf/BetterDiscordPlugins#241]
GuildProfile seems to not be working anymore after the newest update.

**Comment by jaimeadf** [comment]
What in specific is not working?

**Comment by x3221** [comment]
> What in specific is not working?

Nothing really, it just doesn't display anything when I'm clicking on Server Profile

**Comment by jaimeadf** [comment]
What's your plugin version and discord version?

**Comment by x3221** [comment]
> What's your plugin version and discord version?

Plugin version 1.4.3 , can't really find the discord version, it isn't letting me go into the dev tools after the latest update, I do have the latest discord and betterdiscord versions

**Comment by jaimeadf** [comment]
That plugin version is really out of date. You can download the newest version by saving [this raw file](https://raw.githubusercontent.com/jaimeadf/BetterDiscordPlugins/release/dist/GuildProfile/GuildProfile.plugin.js) into your plugins folder.
