### ISSUE TITLE
BiggerStreamPreview no button to click when right clicking on user in a server sharing screen.

### ISSUE THREAD

**Issue by RDP8** [jaimeadf/BetterDiscordPlugins#249]
Do I have to be friends with said person or do I have to be an admin for the server they are screen sharing in?

**Comment by jaimeadf** [comment]
I think discord broke the context menus again. I can't confirm it right now, but I'll check it tomorrow.

**Comment by RDP8** [comment]
Hi,
I believe this hasn't been fixed yet, just wanted to give you a heads up about that.

**Comment by jaimeadf** [comment]
It's broken at the moment.

**Comment by stressatoo** [comment]
Still broken.
