### ISSUE TITLE
Discord crashing when using guild profile 

### ISSUE THREAD

**Issue by Basic6969** [jaimeadf/BetterDiscordPlugins#287]
![image](https://user-images.githubusercontent.com/98833613/163664499-488b7351-6077-4f8f-916a-b2f8c18e59b8.png)

**Comment by maenDisease** [comment]
Additional console error, crashes when opening the guild profile

![image](https://user-images.githubusercontent.com/90428263/163679462-5ae33630-9419-4092-a359-252628c9a88a.png)

**Comment by Debuggerz1** [comment]
It crashes because this `WebpackModules.getByProps('hidePersonalInformation')` returns nothing now, So my quick fix is to just set the hide variable to false *(true makes it show nothing)*

There are two of them

old:

``` 
line 1189: const hide = useStateFromStores([StreamerModeStore], () => StreamerModeStore.hide);
line 1276: const hide = useStateFromStores([GuildRoles_StreamerModeStore], () => GuildRoles_StreamerModeStore.hide);
```
new:
```
const hide = false; // for both
```

**Comment by Basic6969** [comment]
why closed is it fixed?

**Comment by xOnlyFadi** [comment]
> why closed is it fixed?

it was closed because he fixed with the new update

**Comment by Basic6969** [comment]
> > why closed is it fixed?
> 
> it was closed because he fixed with the new update

its still same

**Comment by jaimeadf** [comment]
I released a new version that hopefully fixed the issue this time. Let me know if any problems occur.

**Comment by Basic6969** [comment]
> I released a new version that hopefully fixed the issue this time. Let me know if any problems occur.

thx its fixed
