### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Tydoki** [jaimeadf/BetterDiscordPlugins#3]
I have a bot that auto puts a upvote and downvote on every picture and I was trying to think of a solution you could implement for the bot avatar to not have to show up on every reaction.

Maybe a blacklist for users (aka the bot)
Or a minimum required emoji count (set on a per emoji basis)

I know the solutions I suggested are prob more complicated then what the plugin does... I'm sorry xD

**Comment by jaimeadf** [comment]
Someone had a similar suggestion on the discord server, and we came with the idea to add toggleable options to hide yourself and bots from the reactors that would hide everything when they're the only ones or would show them on the `+` thingy (I don't know how to call it).

And btw don't worry, if you think of any more improvements let me know, no matter how complicated they are.
Sorry for the late response too.
