### ISSUE TITLE
Volume Booster Not Working

### ISSUE THREAD

**Issue by RealSkullton** [jaimeadf/BetterDiscordPlugins#333]
When I put the .js file in my plugin folder it gives me a message shown in the image below
![Screenshot (61)](https://user-images.githubusercontent.com/97701848/180111314-4d8cea12-d62b-4a4a-ad81-05ad769f1836.png)
Idk whats wrong

**Comment by jaimeadf** [comment]
I'm not the owner of `UserVolumeBooster`. Please, create an issue on their repository.
