### ISSUE TITLE
Guildprofiles cant be constructed

### ISSUE THREAD

**Issue by Masono03** [jaimeadf/BetterDiscordPlugins#335]
As the title says. Heres my discord/windows build.

Canary 139299 (bf7a2ab)
BetterDiscord 1.5.3-Hotfix
Host 1.0.48 Windows 10 64-Bit (10.0.19044)

**Comment by XxUnkn0wnxX** [comment]
yep really dead here to on stable
```text
Stable 139391 (896f0fd)
BetterDiscord 1.5.3-Hotfix
Host 0.0.267 OS X 10.15.7 (20.6.0)
```

```text
GuildProfile.plugin.js:415 Uncaught TypeError: Cannot read property 'CONNECTION_OPEN' of undefined
    at GuildProfile.plugin.js:415
    at GuildProfile.plugin.js:1742
    at buildPlugin (GuildProfile.plugin.js:1745)
    at GuildProfile.plugin.js:1752
    at GuildProfile.plugin.js:1811
    at Object.getFileModification (<anonymous>:4:307632)
    at Object..js (<anonymous>:4:267779)
    at Function.o._load (<anonymous>:4:370331)
    at Object.loadAddon (<anonymous>:4:267936)
    at Object.loadAddon (<anonymous>:4:305881)
    at Object.loadAllAddons (<anonymous>:4:270609)
    at Object.initialize (<anonymous>:4:265058)
    at Object.initialize (<anonymous>:4:305091)
    at Object.startup (<anonymous>:4:367101)
(anonymous) @ GuildProfile.plugin.js:415
(anonymous) @ GuildProfile.plugin.js:1742
buildPlugin @ GuildProfile.plugin.js:1745
(anonymous) @ GuildProfile.plugin.js:1752
(anonymous) @ GuildProfile.plugin.js:1811
getFileModification @ VM470:4
(anonymous) @ VM470:4
o._load @ VM470:4
loadAddon @ VM470:4
loadAddon @ VM470:4
loadAllAddons @ VM470:4
initialize @ VM470:4
initialize @ VM470:4
startup @ VM470:4
async function (async)
startup @ VM470:4
(anonymous) @ VM470:4
(anonymous) @ VM470:4
(anonymous) @ VM470:4
(anonymous) @ VM470:9
e.startsWith.e.startsWith.WebFrame.<computed> @ VM75 renderer_init.js:89
(anonymous) @ VM75 renderer_init.js:117
(anonymous) @ VM75 renderer_init.js:101
emit @ VM14 events.js:315
```
<img width="598" alt="Screen Shot 2022-08-02 at 7 14 54 am" src="https://user-images.githubusercontent.com/2242880/182248919-7cd8c0d5-83ff-4a1a-95eb-f3d5b35b6ba0.png">

**Comment by StandingPadAnimations** [comment]
Yep, same here. I think it's related to the new Better Discord update

**Comment by EMREOYUN** [comment]
Same here, without updating BetterDiscord at all

**Comment by EMREOYUN** [comment]
> Its known. Discord broke many Plugins with the last update

_Originally posted by @HypedDomi in https://github.com/Strencher/BetterDiscordStuff/issues/225#issuecomment-1201825082_

**Comment by HypedDomi** [comment]
I fixed the Plugin. Waiting for the [merge](https://github.com/jaimeadf/BetterDiscordPlugins/pull/336). If you cant wait, use this  [file](https://raw.githubusercontent.com/HypedDomi/BetterDiscordPlugins-jaimeadf/release/dist/GuildProfile/GuildProfile.plugin.js)

**Comment by EMREOYUN** [comment]
> I fixed the Plugin. Waiting for the [merge](https://github.com/jaimeadf/BetterDiscordPlugins/pull/336). If you cant wait, use this [file](https://raw.githubusercontent.com/HypedDomi/BetterDiscordPlugins-jaimeadf/release/dist/GuildProfile/GuildProfile.plugin.js)

Tested and working properly

**Comment by Poirot12345T** [comment]
the bug can be spotted on both of BetterDiscord 1.5.3 and 1.5.3-Hotfix. Discord Stable 139460 (ea9eb84), Linux 64bit (5.18.14-Arch1-1);
file suggested by @HypedDomi works fine.

**Comment by XxUnkn0wnxX** [comment]
@HypedDomi This broke on PTB & Canary again with your fixed ver
```text
Ptb 139684 (95340d3)
BetterDiscord 1.5.3-Hotfix2
Host 0.0.63 OS X 10.15.7 (20.6.0)
```

Console Log:
```text
35b172dbf615e7730874.js:4267 Uncaught TypeError: Cannot read property 'register' of undefined
    at new e (35b172dbf615e7730874.js:4267)
    at new MemberCountsStore (GuildProfile.plugin.js:414)
    at GuildProfile.plugin.js:430
    at GuildProfile.plugin.js:1755
    at buildPlugin (GuildProfile.plugin.js:1758)
    at GuildProfile.plugin.js:1765
    at GuildProfile.plugin.js:1824
    at Object.getFileModification (<anonymous>:4:307640)
    at Object..js (<anonymous>:4:267787)
    at Function.o._load (<anonymous>:4:370339)
    at Object.loadAddon (<anonymous>:4:267944)
    at Object.loadAddon (<anonymous>:4:305889)
    at Object.loadAllAddons (<anonymous>:4:270617)
    at Object.initialize (<anonymous>:4:265066)
    at Object.initialize (<anonymous>:4:305099)
    at Object.startup (<anonymous>:4:367109)
e @ 35b172dbf615e7730874.js:4267
MemberCountsStore @ GuildProfile.plugin.js:414
(anonymous) @ GuildProfile.plugin.js:430
(anonymous) @ GuildProfile.plugin.js:1755
buildPlugin @ GuildProfile.plugin.js:1758
(anonymous) @ GuildProfile.plugin.js:1765
(anonymous) @ GuildProfile.plugin.js:1824
getFileModification @ VM470:4
(anonymous) @ VM470:4
o._load @ VM470:4
loadAddon @ VM470:4
loadAddon @ VM470:4
loadAllAddons @ VM470:4
initialize @ VM470:4
initialize @ VM470:4
startup @ VM470:4
async function (async)
startup @ VM470:4
(anonymous) @ VM470:4
(anonymous) @ VM470:4
(anonymous) @ VM470:4
(anonymous) @ VM470:9
e.startsWith.e.startsWith.WebFrame.<computed> @ VM75 renderer_init.js:89
(anonymous) @ VM75 renderer_init.js:117
(anonymous) @ VM75 renderer_init.js:101
emit @ VM14 events.js:315
onMessage @ VM75 renderer_init.js:93
```
<img width="696" alt="GuildProfile" src="https://user-images.githubusercontent.com/2242880/182522583-64b31561-d322-48a3-be03-62768646ccb0.png">

**Comment by Masono03** [comment]
Broken again as of today.

Canary 139699 (bdc9502)
BetterDiscord 1.5.3-Hotfix2
Host 1.0.48 Windows 10 64-Bit (10.0.19044)

**Comment by XxUnkn0wnxX** [comment]
Since the recent update to ZeresPluginLibrary V2.0.4, & GuildProfile V1.6.3 this works everywhere again..

**Comment by EMREOYUN** [comment]
> I fixed the Plugin. Waiting for the [merge](https://github.com/jaimeadf/BetterDiscordPlugins/pull/336). If you cant wait, use this [file](https://raw.githubusercontent.com/HypedDomi/BetterDiscordPlugins-jaimeadf/release/dist/GuildProfile/GuildProfile.plugin.js)

@XxUnkn0wnxX Yes, it has been solved already.
