### ISSUE TITLE
[Bug] Use links to the new website

### ISSUE THREAD

**Issue by dav1312** [jaimeadf/BetterDiscordPlugins#34]
The link to ZeresPluginLibrary use the old website (e.g [GuildProfile](https://github.com/jaimeadf/BetterDiscordPlugins/blob/b04c4c5a5589d7927ba518909d197606ca71df17/dist/GuildProfile/GuildProfile.plugin.js#L1385))

Change it to the new link: https://betterdiscord.app/Download?id=9

**Comment by jaimeadf** [comment]
Thanks, I completely forgot about that link.
