### ISSUE TITLE
(GuildProfile) Plugin had no exports or @name properly

### ISSUE THREAD

**Issue by Keler69** [jaimeadf/BetterDiscordPlugins#342]
BetterDiscord version:
Stable 141269 (c0a9e60)
BetterDiscord 1.6.2
Host 1.0.9006 Windows 10 64-Bit (10.0.22000)

**Comment by dragonunitedtm** [comment]
ditto

**Comment by QXvH1** [comment]
ditto.
weird, the plugin seems to have both

**Comment by Drflash55** [comment]
V1.4.5 of GuildProfile works as intended.
Getting it from Plugin Repo won't work ATM because it hasn't updated, but you can grab the source and manually change the .js file so that it loads correctly.
