### ISSUE TITLE
[Feature Request] (GuildProfile) Hide Joined/Last Message times for "Home" Screen

### ISSUE THREAD

**Issue by bbeenn1** [jaimeadf/BetterDiscordPlugins#344]
When viewing the Friends list "Joined At" shows "(!) Failed to Fetch" and Last Message shows "(!) Cannot resolve channel/guild id."

This is expected behavior but just looks odd to uninformed users.

When you go into a conversation the last message date populates correctly, but the joined at date remains in an error state.

I am uncertain if any logic could handle this to simply not display on the "Home" and Direct Messages screens when errored but it would make it just a bit more graceful in my mind.

**Comment by jaimeadf** [comment]
GuildProfile doesn't create any "Last Message" section. Are you sure that GuildProfile is responsible for that?

**Comment by bbeenn1** [comment]
Ah, I found that one was a separate plugin, I may have a few that actually handle that and got them crossed.
LastMessageDate by DevilBro (maybe) and UserDetails by Strencher (more likely) are apparently where I should be looking.

Thank You for the prompt response!
