### ISSUE TITLE
BiggerStreamPreview broken

### ISSUE THREAD

**Issue by Bekston** [jaimeadf/BetterDiscordPlugins#372]
It doesn't even load.

Error message: "An error was encountered while trying to load this plugin."

**Comment by KaanAlper** [comment]
Agree with you

**Comment by LichLord91** [comment]
+1

**Comment by robertogogoni** [comment]
Yep. It would be the very first experience with the plugin, but it's completely broken. Any of you know anything similar? Maybe discord previews without entering the preview itself? Thanks in advance!

**Comment by merri1400** [comment]
The plugins all broke in September and the dev is busy, you'll either have to wait to see if they decide to fix it in the future or see if someone else decides to fix it.

**Comment by Tharki-God** [comment]
well if someone can get me permission i can fix it and post it on my repo

**Comment by robertogogoni** [comment]
Hey! You made it work. Thank you, man! @Tharki-God
