### ISSUE TITLE
WhoReacted disappearing all reacts in chat

### ISSUE THREAD

**Issue by blueberrylava** [jaimeadf/BetterDiscordPlugins#404]
I installed the latest version of WhoReacted, and after enabling it all reactions disappeared. I tested disabling all other plugins to find a conflict but I wasn't able to find anything.

**Comment by itzahoneybadger** [comment]
I'm also having this issue. The only way I can get the reactions to show is to disable the WhoReacted Plugin.

**Comment by KaoticOblivion** [comment]
3rding this issue. I also only had this issue with WhoReacted enabled with v1.3 no other plugins hide the reactions

**Comment by cyrus01337** [comment]
For some reason, the `span` tags simply don't render. I wonder if there's an issue with a particular condition due to Discord updates.

**Comment by iDeparture** [comment]
its working fine now <3
