### ISSUE TITLE
hiding blocked members

### ISSUE THREAD

**Issue by Poirot12345T** [jaimeadf/BetterDiscordPlugins#49]
Hi, would it be possible to add a possibility of not showing a blocked member's avatar?
_I'm sorry, but I can't do it on my own as I'm not a JavaScript programmer, and it was just a idea_

**Comment by jaimeadf** [comment]
It's possible, and it's not a hard feature to be added since most of the filtering process is already done. I'm looking forward to adding this in the next update so, if anyone wants to do it, feel free to.
