### ISSUE TITLE
[Bug Report] (Plugin: BiggerStreamPreview) Allow it to work in group calls

### ISSUE THREAD

**Issue by Yakov5776** [jaimeadf/BetterDiscordPlugins#81]
Currently, if you have [BiggerStreamPreview](https://github.com/jaimeadf/BetterDiscordPlugins/tree/release/src/BiggerStreamPreview), It doesn't seem to work on people screensharing in group calls.

Result:
![Discord_J5HHePoy2U](https://user-images.githubusercontent.com/28637006/122291180-8711cc80-cec2-11eb-8b74-c2f258b5e0db.png)

**Comment by jaimeadf** [comment]
It isn't available in that context menu yet, but you can access it via the user's context menu for all call types.
